### ISSUE TITLE
blat_best.py error

### ISSUE THREAD

**Issue by ma-diroma** [jason-weirather/IDP#1]
Hi,

I am trying to use IDP (the latest version). I tested it on your small example data and it perfectly worked. I am trying to analyze my sample, but I got this error

```
Traceback (most recent call last):
  File "/home/madiroma/bin/IDP_0.1.9/bin/blat_best.py", line 33, in <module>
    if Qname == ls[9]:
IndexError: list index out of range
```

Long reads were renamed by seqtools, so this is the content of my LR_notailspolyA.fa.aa.psl (input to blat_best.py) 

```
psLayout version 3

match   mis-    rep.    N's     Q gap   Q gap   T gap   T gap   strand  Q               Q       Q       Q       T               T       T       T       block   blockSizes      qStarts  tStarts
        match   match           count   bases   count   bases           name            size    start   end     name            size    start   end     count
---------------------------------------------------------------------------------------------------------------------------------------------------------------
286     18      0       0       2       14      2       316     +       m150101_010101_11111_c111111111111111111_s1_p0/1/ccs    659     341     659     chrY    59373566        1305963 1306583 4       25,99,56,124,   341,367,479,535,        1305963,1305988,1306097,1306459,
616     24      0       0       5       19      2       8       +       m150101_010101_11111_c111111111111111111_s1_p0/1/ccs    659     0       659     chrX    155270560       32224518        32225166        6       105,35,146,71,269,14,   0,109,153,300,372,645,  32224518,32224624,32224666,32224812,32224883,32225152,
994     46      0       0       2       8       1       6       +       m150101_010101_11111_c111111111111111111_s1_p0/2/ccs    1048    0       1048    chr9    141213431       14921375        14922421        3       168,836,36,     0,175,1012,     14921375,14921549,14922385,

...
```

It seems there is some problem in the name field. Could you please help me? 
Thanks,
Maria Angela

**Comment by Huangyizhong** [comment]
> Hi,
> 
> I am trying to use IDP (the latest version). I tested it on your small example data and it perfectly worked. I am trying to analyze my sample, but I got this error
> 
> ```
> Traceback (most recent call last):
>   File "/home/madiroma/bin/IDP_0.1.9/bin/blat_best.py", line 33, in <module>
>     if Qname == ls[9]:
> IndexError: list index out of range
> ```
> 
> Long reads were renamed by seqtools, so this is the content of my LR_notailspolyA.fa.aa.psl (input to blat_best.py)
> 
> ```
> psLayout version 3
> 
> match   mis-    rep.    N's     Q gap   Q gap   T gap   T gap   strand  Q               Q       Q       Q       T               T       T       T       block   blockSizes      qStarts  tStarts
>         match   match           count   bases   count   bases           name            size    start   end     name            size    start   end     count
> ---------------------------------------------------------------------------------------------------------------------------------------------------------------
> 286     18      0       0       2       14      2       316     +       m150101_010101_11111_c111111111111111111_s1_p0/1/ccs    659     341     659     chrY    59373566        1305963 1306583 4       25,99,56,124,   341,367,479,535,        1305963,1305988,1306097,1306459,
> 616     24      0       0       5       19      2       8       +       m150101_010101_11111_c111111111111111111_s1_p0/1/ccs    659     0       659     chrX    155270560       32224518        32225166        6       105,35,146,71,269,14,   0,109,153,300,372,645,  32224518,32224624,32224666,32224812,32224883,32225152,
> 994     46      0       0       2       8       1       6       +       m150101_010101_11111_c111111111111111111_s1_p0/2/ccs    1048    0       1048    chr9    141213431       14921375        14922421        3       168,836,36,     0,175,1012,     14921375,14921549,14922385,
> 
> ...
> ```
> 
> It seems there is some problem in the name field. Could you please help me?
> Thanks,
> Maria Angela

Hi, Maria
  Have you solved this problem? I also have the same  problem in testing the example data? How do you conduct the analysis with the example data? When you analyze your data, do you use the CCS dara or others?
Thanks 
Tony
